(defun MEMALL (atm L)
   (cond ( (NULL L) NIL )
         ( (ATOM L) (EQL atm L) )
         ( T (OR (MEMALL atm (CAR L))
                 (MEMALL atm (CDR L)) ) )
   )
)

(defun SETUNION (set1 set2)
   (cond ( (NULL set1) set2)
      ( (MEMALL (CAR set1) set2)
         (SETUNION (CDR set1) set2)
      )
      ( T (CONS (CAR set1)
            (SETUNION (CDR set1) set2)
          )
      )
   )
) 

(setf unio (setunion '(x y z) '(v w x z)))
(print unio)
