#!/bin/bash

echo '#include <stdio.h>' >> "$1"
echo '#include <stdlib.h>' >> "$1"
echo '#include <string.h>' >> "$1"
echo '' >> "$1"
echo 'int main(int argc, char *argv[])' >> "$1"
echo '{' >> "$1"
echo '    ' >> "$1"
echo '    return 0;' >> "$1"
echo '}' >> "$1"
