#!/usr/bin/perl

while(<>){
    if(/sendmail/ and /server/ or 
       /sendmail/ and /user open/ ){
        @fields = split(' ', $_);
        my $mpid = @fields[1];
        my $mip = @fields[12];
        $mip =~ s/\.:$//;
        $mip =~ s/^.*@//;
        if($mip =~ /\./){
            print "$mip   $mpid\n";
        }
    }
}
