#!/usr/bin/perl

use warnings;

while($_ = shift) {
    open(MH, $_);
    while(<MH>) {
        chop $_;
        print $_,"\n";
        walk_dir($_);
    }
}

sub walk_dir {
    my $parent = shift @_;
    opendir(my $DH, $parent) || die $!;
    while(readdir($DH)) {
        next if $_ eq "." or $_ eq "..";
        $fname = "$parent/$_";
        if(-d $fname) {
            walk_dir($fname);
            next;
        }
        if($fname =~ /\/core$/) {
            print "rm $fname\n";
        }
    }
    closedir($DH);
}
