#!/usr/bin/perl

open(F1, shift) or die $!;
open(F2, shift) or die $!;

$l1 = <F1>;
$l2 = <F2>;

while($l1 || $l2) {
    if($l1) {
        print $l1;
    }
    if($l2) {
        print $l2;
    }
    $l1 = <F1>;
    $l2 = <F2>;
}
