all:
	gcc -Wall -g -c -o prog1.o prog1.c
	gcc -Wall -g -c -o prog2.o prog2.c
	gcc -Wall -g -c -o prog3.o prog3.c
	gcc -Wall -g -c -o prog4.o prog4.c
	gcc -Wall -g -c -o prog5.o prog5.c
	gcc -Wall -g -o driver prog1.o prog2.o prog3.o prog4.o prog5.o driver.c
prog1:
	gcc -Wall -g -c -o prog1.o prog1.c
	gcc -Wall -g -o driver prog1.o driver.c
prog2:
	gcc -Wall -g -c -o prog2.o prog2.c
	gcc -Wall -g -o driver prog2.o driver.c
prog3:
	gcc -Wall -g -c -o prog3.o prog3.c
	gcc -Wall -g -o driver prog3.o driver.c
prog4:
	gcc -Wall -g -c -o prog4.o prog4.c
	gcc -Wall -g -o driver prog4.o driver.c
prog5:
	gcc -Wall -g -c -o prog5.o prog5.c
	gcc -Wall -g -o driver prog5.o driver.c
